### PR TITLE
Update to `twilight` 0.16

### PR DESCRIPTION
**Pull request by decahedron1**

### CODE REVIEW

**Comment by AlvaroMS25** [comment]
I'm not sure about upgrading to twilight 0.16 yet, it's still a release candidate, so things may change

(please correct me if i'm wrong tho)

**Comment by decahedron1** [comment]
You're 100% right, which is why I made this PR a draft. I'll update it when 0.16 gets a stable release.

**Comment by AlvaroMS25** [comment]
I'm going to move this draft to the branch `next` so we can start working with it

**Comment by AlvaroMS25** [comment]
Merged now!

**Pull request merged**
